# Generated by Django 4.0.1 on 2022-01-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='LoginData',
        ),
    ]
